### ISSUE TITLE
Phase 1

### ISSUE THREAD

**Issue by AllenFang** [revamp-with-react/ungit-react#1]
**Target**: initial load successfully for the route of `/repository?path=xxx`
1. We can see the git graph without any critical broken
2. Skip any user action events, it will be implement on phase 2, for now, we focus on displaying correct data and UI

**Tasks**
- [ ] Implement Components
  - [ ] Implement graph part
  - [ ] Implement the remain parts except the graph part
- [ ] Find a appropriate way to integrate following common function (Please help to add)
  - [ ] [main.js#L17-L47](https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L17-L47)
  - [ ] [main.js#L49-L95](https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L49-L95)
  - [ ] [main.js#L100-L110](https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L100-L110)
  - [ ] [main.js#L112-L123](https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L112-L123)
  - [ ] [main.js#L201-L203](https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L201-L203)
- [ ] Find some solution to solve transfer the using of `jQuery UI` and `bootstrap.js`
- [ ] Create a basic `redux` and `react` scratch applicaton.
- [ ] Add ESLint

**Comment by CYBAI** [comment]
Need confirmation

- [ ] For [main.js#L17-L47][]
- About [**rAF**][rAF], if we only need to support modern browser, I think we don't need to use a polyfill
- About [**bootstrap-tooltip**][bootstrap-tooltip], maybe we can use components like [react-tooltip][], [tooltip][], or [redux-tooltip][]. I think we need to check which we should use.

- [ ] For [main.js#L112-L123][],
- I think we can write a **Title** component or use something like [react-helmet][]

- [ ] For [main.js#L201-L203][],
- We can try [react-dnd][]

[main.js#L17-L47]: https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L17-L47
[main.js#L112-L123]: https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L112-L123
[main.js#L201-L203]: https://github.com/revamp-with-react/ungit-react/blob/master/public/source/main.js#L201-L203
[rAF]: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
[bootstrap-tooltip]: https://www.w3schools.com/bootstrap/bootstrap_tooltip.asp
[react-tooltip]: https://github.com/wwayne/react-tooltip
[tooltip]: https://github.com/react-component/tooltip
[redux-tooltip]: https://github.com/kuy/redux-tooltip
[react-helmet]: https://github.com/nfl/react-helmet
[react-dnd]: https://github.com/react-dnd/react-dnd
